// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDezIPC8J0MMc3uVRdf273-gcWvgIJWxTY',
    appId: '1:21071051152:web:094f231203879ca41ddb15',
    messagingSenderId: '21071051152',
    projectId: 'frontend-6b537',
    authDomain: 'frontend-6b537.firebaseapp.com',
    storageBucket: 'frontend-6b537.firebasestorage.app',
    measurementId: 'G-RJH2H22TQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa3nxt3CvF9qiyrRv_9ASHhyT4Uhnoh3k',
    appId: '1:21071051152:android:30c13e6d072248471ddb15',
    messagingSenderId: '21071051152',
    projectId: 'frontend-6b537',
    storageBucket: 'frontend-6b537.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0b6jheOFE7y5I5bLG51UWO7mbdSLH18o',
    appId: '1:21071051152:ios:0cee5719b0a22bba1ddb15',
    messagingSenderId: '21071051152',
    projectId: 'frontend-6b537',
    storageBucket: 'frontend-6b537.firebasestorage.app',
    iosClientId: '21071051152-6nc312au31bhfgumak9u29og9u49ri22.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0b6jheOFE7y5I5bLG51UWO7mbdSLH18o',
    appId: '1:21071051152:ios:0cee5719b0a22bba1ddb15',
    messagingSenderId: '21071051152',
    projectId: 'frontend-6b537',
    storageBucket: 'frontend-6b537.firebasestorage.app',
    iosClientId: '21071051152-6nc312au31bhfgumak9u29og9u49ri22.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDezIPC8J0MMc3uVRdf273-gcWvgIJWxTY',
    appId: '1:21071051152:web:705c50c9bb9cbf1c1ddb15',
    messagingSenderId: '21071051152',
    projectId: 'frontend-6b537',
    authDomain: 'frontend-6b537.firebaseapp.com',
    storageBucket: 'frontend-6b537.firebasestorage.app',
    measurementId: 'G-YZ663JK54Q',
  );
}
